- name: enable firewalld service
  become: yes
  service:
    name: firewalld
    state: started
    enabled: yes
  tags: firewalld

- name: configure firewalld
  become: yes
  firewalld: "port={{item}}/tcp permanent=true state=enabled"
  notify: restart firewalld
  with_items: "{{firewalld_open_ports}}"
  tags: firewalld
