- name: copy nginx.conf
  become: yes
  template:
    src: "../templates/{{ item }}.j2"
    dest: "{{nginx_path}}/{{ item }}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
    validate: 'nginx -tc %s'
  with_items:
    - nginx.conf
  notify:
    - reload nginx

- name: create sites-enabled folder
  become: yes
  file: 
    path: "{{nginx_path}}/sites-enabled" 
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644

- name: create sites-available folder
  become: yes
  file: 
    path: "{{nginx_path}}/sites-available"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644

- name: make rules directory
  become: yes
  file:
    path: "{{nginx_path}}/rules"
    state: directory

- name: copy other useful config files
  become: yes
  copy:
    src: files/{{item}}
    dest: "{{nginx_path}}/rules/{{item}}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  with_items:
    - gzip.conf
    - security.conf
  notify:
    - reload nginx

- name: copy vhosts
  become: yes
  copy:
    content: "{{item.content}}"
    dest: "{{nginx_path}}/sites-available/{{ item.name }}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  with_items: "{{nginx_vhosts|default([])}}"
  notify:
    - reload nginx

- name: create vhosts symlinks
  become: yes
  file: 
    src: "{{nginx_path}}/sites-available/{{ item.name }}" 
    dest: "{{nginx_path}}/sites-enabled/{{ item.name }}" 
    state: link
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  with_items: "{{nginx_vhosts|default([])}}"
  notify:
    - reload nginx

- name: make sure the default site is not there
  become: yes
  file:
    path: "{{nginx_path}}/sites-enabled/default"
    state: absent
  notify:
    - reload nginx
  register: isdefault

- name: reload nginx
  become: yes
  shell: nginx -s reload
  when: isdefault.changed

- name: configure fail2ban for nginx
  become: yes
  copy:
    dest: /etc/fail2ban/jail.d/nginx
    content: |
     [nginx-http-auth]
     enabled=true
     [nginx-botsearch]
     enabled=true
  notify:
    - restart fail2ban
  when: nginx_fail2ban is defined and nginx_fail2ban
