- name: copy nginx.conf
  template:
    src: "../templates/{{ item }}.j2"
    dest: "{{nginx_path}}/{{ item }}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  with_items:
    - nginx.conf
  notify:
    - restart nginx

- name: create sites-enabled folder
  file: 
    path: "{{nginx_path}}/sites-enabled" 
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644

- name: create sites-available folder
  file: 
    path: "{{nginx_path}}/sites-available"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644

- name: copy vhosts
  copy:
    content: "{{item.content}}"
    dest: "{{nginx_path}}/sites-available/{{ item.name }}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  with_items: "{{nginx_vhosts|default([])}}"
  notify:
    - restart nginx

- name: create vhosts symlinks
  file: 
    src: "{{nginx_path}}/sites-available/{{ item.name }}" 
    dest: "{{nginx_path}}/sites-enabled/{{ item.name }}" 
    state: link
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  with_items: "{{nginx_vhosts|default([])}}"
  notify:
    - restart nginx

- name: make sure the default site is not there
  file:
    path: "{{nginx_path}}/sites-enabled/default"
    state: absent
  become: yes
  notify:
    - restart nginx

- name: configure fail2ban for nginx
  copy:
    dest: /etc/fail2ban/jail.d/nginx
    content: |
     [nginx-http-auth]
     enabled=true
     [nginx-botsearch]
     enabled=true
  become: yes
  notify:
    - restart fail2ban
  when: nginx_fail2ban is defined and nginx_fail2ban
