- name: create ssl base folder
  become: yes
  file: 
    path: "{{nginx_ssl_store_path}}" 
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0600
    setype: httpd_config_t

- name: check if dhparams are generated
  become: yes
  stat: 
    path: "{{nginx_ssl_store_path}}/dhparams.pem"
  register: st

- name: generate dhparams
  become: yes
  shell: 'openssl dhparam -out {{nginx_ssl_store_path}}/dhparams.pem {{dh_size}}'
  when: st.stat.exists == False
  notify:
  - restart nginx

- name: chown dhparams
  become: yes
  file: 
    path: "{{nginx_ssl_store_path}}/dhparams.pem" 
    state: file
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0600
    setype: httpd_config_t
  notify:
  - restart nginx

- name: copy ssl-certificates and keys
  become: yes
  copy:
    content: "{{ item.content }}"
    dest: "{{nginx_ssl_store_path}}/{{ item.name }}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0600
    setype: httpd_config_t
  with_items: "{{nginx_copy_ssl|default([])}}"
  notify:
    - restart nginx
